apiVersion: v1
kind: ServiceAccount
metadata:
  name: frontend-sa
  namespace: {{ .Values.namespace }}
  labels:
    app: frontend
    {{- include "caresync.labels" . | nindent 4 }}
  annotations:
    eks.amazonaws.com/role-arn: "arn:aws:iam::{{ .Values.awsAccountId }}:role/caresync-dev-frontend-role"
automountServiceAccountToken: true
