#!/usr/bin/env node
/**
 * fetch-secrets.js
 *
 * Runs at container startup BEFORE prisma migrate deploy.
 * Fetches DATABASE_URL, JWT_SECRET, JWT_REFRESH_SECRET from AWS Secrets Manager
 * and writes them to /tmp/runtime-secrets.env so docker-entrypoint.sh can
 * source them before Prisma needs DATABASE_URL.
 *
 * Design decisions:
 *   - Pure CommonJS — no TypeScript compilation, no ts-node required.
 *   - Uses @aws-sdk/client-secrets-manager already in node_modules/
 *   - Writes to /tmp/runtime-secrets.env (world-readable only for this process tree)
 *   - Values are single-quoted with internal single-quotes escaped, which is
 *     safe for any secret value including those containing spaces, $, ``, etc.
 *   - If AWS_SECRETS_MANAGER_SECRET_NAME is unset, writes an empty file and
 *     exits 0 so local docker-compose (without Secrets Manager) still works.
 *   - Exits non-zero on any AWS or JSON error so the entrypoint fails fast
 *     with a clear message rather than a cryptic Prisma P1012.
 */

'use strict';

const fs = require('fs');
const path = require('path');

const OUTPUT_FILE = '/tmp/runtime-secrets.env';
const REQUIRED_KEYS = ['DATABASE_URL', 'JWT_SECRET', 'JWT_REFRESH_SECRET'];

async function main() {
  const secretName = process.env.AWS_SECRETS_MANAGER_SECRET_NAME;

  if (!secretName) {
    // Local development: DATABASE_URL comes from .env via docker-compose.
    // Write an empty file so the entrypoint source command always succeeds.
    fs.writeFileSync(OUTPUT_FILE, '# No Secrets Manager secret name configured\n', 'utf8');
    console.log('ℹ️  AWS_SECRETS_MANAGER_SECRET_NAME not set — skipping Secrets Manager fetch');
    return;
  }

  const region = process.env.AWS_REGION || 'us-east-1';
  console.log(`🔐 Fetching secrets from AWS Secrets Manager: ${secretName} (${region})`);

  // Require the SDK from the installed node_modules (already a production dependency).
  const { SecretsManagerClient, GetSecretValueCommand } = require(
    path.join('/app', 'node_modules', '@aws-sdk', 'client-secrets-manager')
  );

  const client = new SecretsManagerClient({ region });

  let response;
  try {
    response = await client.send(new GetSecretValueCommand({ SecretId: secretName }));
  } catch (err) {
    console.error('❌ Failed to retrieve secret from AWS Secrets Manager.');
    console.error(`   Secret name : ${secretName}`);
    console.error(`   Region      : ${region}`);
    console.error(`   Error       : ${err.message}`);
    console.error('');
    console.error('Checklist:');
    console.error('  1. Is the IAM instance profile attached to this EC2 instance?');
    console.error('  2. Does the IAM role have secretsmanager:GetSecretValue permission?');
    console.error('  3. Does the secret exist in the correct region?');
    console.error('  4. Has the secret been populated via aws secretsmanager put-secret-value?');
    process.exit(1);
  }

  if (!response.SecretString) {
    console.error(`❌ Secret "${secretName}" exists but has no value (SecretString is empty).`);
    console.error('   Run: aws secretsmanager put-secret-value --secret-id ' + secretName);
    console.error('   Required JSON keys: DATABASE_URL, JWT_SECRET, JWT_REFRESH_SECRET');
    process.exit(1);
  }

  let secrets;
  try {
    secrets = JSON.parse(response.SecretString);
  } catch (err) {
    console.error(`❌ Secret "${secretName}" is not valid JSON.`);
    console.error('   Expected format: {"DATABASE_URL":"...","JWT_SECRET":"...","JWT_REFRESH_SECRET":"..."}');
    process.exit(1);
  }

  // Validate all required keys are present and non-empty.
  const missing = REQUIRED_KEYS.filter(k => !secrets[k]);
  if (missing.length > 0) {
    console.error(`❌ Secret "${secretName}" is missing required keys: ${missing.join(', ')}`);
    console.error('   Add them via: aws secretsmanager put-secret-value ...');
    process.exit(1);
  }

  // Write shell export statements to the output file.
  // Single-quote wrapping handles values that contain spaces, $, backticks, etc.
  // Internal single-quotes are escaped as: '  →  '\''
  const lines = ['# Generated by fetch-secrets.js — do not edit\n'];
  for (const key of REQUIRED_KEYS) {
    const escaped = String(secrets[key]).replace(/'/g, "'\\''");
    lines.push(`export ${key}='${escaped}'\n`);
  }

  fs.writeFileSync(OUTPUT_FILE, lines.join(''), { mode: 0o600 });
  console.log(`✅ Secrets written to ${OUTPUT_FILE}`);
}

main().catch(err => {
  // Catch unexpected errors (e.g. require() failure for SDK).
  console.error('❌ Unexpected error in fetch-secrets.js:', err.message);
  process.exit(1);
});
