variable "cluster_name" {}
variable "vpc_id" {}
variable "subnet_ids" {}
variable "cluster_sg_id" {}
variable "node_sg_id" {}
variable "kms_key_arn" {}
variable "node_instance_type" {}
variable "node_min_size" {}
variable "node_max_size" {}
variable "node_desired_size" {}