apiVersion: v1
kind: ConfigMap
metadata:
  name: frontend-config
  namespace: {{ .Values.namespace }}
data:
  env-config.js: |
    window._env_ = {
      API_BASE_URL: "{{ .Values.apiBaseUrl }}"
    };
