apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
  namespace: {{ .Values.namespace }}
  labels:
    app: frontend
    {{- include "caresync.labels" . | nindent 4 }}
spec:
  replicas: 2
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
        {{- include "caresync.selectorLabels" . | nindent 8 }}
    spec:
      serviceAccountName: frontend-sa
      securityContext:
        fsGroup: 1000
      topologySpreadConstraints:
      - maxSkew: 1
        topologyKey: topology.kubernetes.io/zone
        whenUnsatisfiable: DoNotSchedule
        labelSelector:
          matchLabels:
            app: frontend
      volumes:
      - name: env-config
        configMap:
          name: frontend-config
      containers:
      - name: frontend
        image: "{{ .Values.services.frontend.repository }}:{{ .Values.services.frontend.tag }}"
        imagePullPolicy: Always
        ports:
        - containerPort: {{ .Values.services.frontend.port }}
        volumeMounts:
        - name: env-config
          mountPath: /usr/share/nginx/html/env-config.js
          subPath: env-config.js
        envFrom:
        - secretRef:
            name: {{ .Values.secrets.name }}
        securityContext:
          allowPrivilegeEscalation: false
          runAsNonRoot: true
          runAsUser: 1000
        resources:
          requests:
            cpu: "100m"
            memory: "128Mi"
          limits:
            cpu: "500m"
            memory: "512Mi"
        livenessProbe:
          httpGet:
            path: /
            port: {{ .Values.services.frontend.port }}
          initialDelaySeconds: 15
          periodSeconds: 20
        readinessProbe:
          httpGet:
            path: /
            port: {{ .Values.services.frontend.port }}
          initialDelaySeconds: 5
          periodSeconds: 10
